# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/bms_id_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_bmsid_update_dialog(object):
    def setupUi(self, bmsid_update_dialog):
        bmsid_update_dialog.setObjectName("bmsid_update_dialog")
        bmsid_update_dialog.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(14)
        bmsid_update_dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(bmsid_update_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_38 = QtWidgets.QLabel(bmsid_update_dialog)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 0, 0, 1, 1)
        self.pushButton_write_bms_id = QtWidgets.QPushButton(bmsid_update_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_write_bms_id.sizePolicy().hasHeightForWidth())
        self.pushButton_write_bms_id.setSizePolicy(sizePolicy)
        self.pushButton_write_bms_id.setObjectName("pushButton_write_bms_id")
        self.gridLayout.addWidget(self.pushButton_write_bms_id, 1, 0, 1, 3)
        self.lineEdit_new_bmsid = QtWidgets.QLineEdit(bmsid_update_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_new_bmsid.sizePolicy().hasHeightForWidth())
        self.lineEdit_new_bmsid.setSizePolicy(sizePolicy)
        self.lineEdit_new_bmsid.setMaxLength(8)
        self.lineEdit_new_bmsid.setObjectName("lineEdit_new_bmsid")
        self.gridLayout.addWidget(self.lineEdit_new_bmsid, 0, 1, 1, 1)

        self.retranslateUi(bmsid_update_dialog)
        QtCore.QMetaObject.connectSlotsByName(bmsid_update_dialog)

    def retranslateUi(self, bmsid_update_dialog):
        _translate = QtCore.QCoreApplication.translate
        bmsid_update_dialog.setWindowTitle(_translate("bmsid_update_dialog", "BMS ID Update"))
        self.label_38.setText(_translate("bmsid_update_dialog", "New BMS ID:"))
        self.pushButton_write_bms_id.setText(_translate("bmsid_update_dialog", "Write"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bmsid_update_dialog = QtWidgets.QWidget()
    ui = Ui_bmsid_update_dialog()
    ui.setupUi(bmsid_update_dialog)
    bmsid_update_dialog.show()
    sys.exit(app.exec_())
