# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/confirm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirm_dialog(object):
    def setupUi(self, confirm_dialog):
        confirm_dialog.setObjectName("confirm_dialog")
        confirm_dialog.resize(404, 300)
        font = QtGui.QFont()
        font.setPointSize(14)
        confirm_dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(confirm_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_confirm = QtWidgets.QLabel(confirm_dialog)
        self.label_confirm.setObjectName("label_confirm")
        self.gridLayout.addWidget(self.label_confirm, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.pushButton_confirm_cancel = QtWidgets.QPushButton(confirm_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_confirm_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_confirm_cancel.setSizePolicy(sizePolicy)
        self.pushButton_confirm_cancel.setObjectName("pushButton_confirm_cancel")
        self.gridLayout.addWidget(self.pushButton_confirm_cancel, 1, 1, 1, 1)
        self.pushButton_confirm_yes = QtWidgets.QPushButton(confirm_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_confirm_yes.sizePolicy().hasHeightForWidth())
        self.pushButton_confirm_yes.setSizePolicy(sizePolicy)
        self.pushButton_confirm_yes.setObjectName("pushButton_confirm_yes")
        self.gridLayout.addWidget(self.pushButton_confirm_yes, 1, 0, 1, 1)

        self.retranslateUi(confirm_dialog)
        QtCore.QMetaObject.connectSlotsByName(confirm_dialog)

    def retranslateUi(self, confirm_dialog):
        _translate = QtCore.QCoreApplication.translate
        confirm_dialog.setWindowTitle(_translate("confirm_dialog", "Prompt"))
        self.label_confirm.setText(_translate("confirm_dialog", "N/A"))
        self.pushButton_confirm_cancel.setText(_translate("confirm_dialog", "Cancel"))
        self.pushButton_confirm_yes.setText(_translate("confirm_dialog", "Yes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    confirm_dialog = QtWidgets.QWidget()
    ui = Ui_confirm_dialog()
    ui.setupUi(confirm_dialog)
    confirm_dialog.show()
    sys.exit(app.exec_())
