# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/sensors_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sensors_dialog(object):
    def setupUi(self, sensors_dialog):
        sensors_dialog.setObjectName("sensors_dialog")
        sensors_dialog.resize(316, 207)
        font = QtGui.QFont()
        font.setPointSize(14)
        sensors_dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(sensors_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_dis_4 = QtWidgets.QCheckBox(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_dis_4.sizePolicy().hasHeightForWidth())
        self.checkBox_dis_4.setSizePolicy(sizePolicy)
        self.checkBox_dis_4.setObjectName("checkBox_dis_4")
        self.gridLayout.addWidget(self.checkBox_dis_4, 0, 2, 1, 1)
        self.checkBox_dis_2 = QtWidgets.QCheckBox(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_dis_2.sizePolicy().hasHeightForWidth())
        self.checkBox_dis_2.setSizePolicy(sizePolicy)
        self.checkBox_dis_2.setObjectName("checkBox_dis_2")
        self.gridLayout.addWidget(self.checkBox_dis_2, 1, 0, 1, 1)
        self.checkBox_dis_5 = QtWidgets.QCheckBox(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_dis_5.sizePolicy().hasHeightForWidth())
        self.checkBox_dis_5.setSizePolicy(sizePolicy)
        self.checkBox_dis_5.setObjectName("checkBox_dis_5")
        self.gridLayout.addWidget(self.checkBox_dis_5, 1, 2, 1, 1)
        self.checkBox_dis_1 = QtWidgets.QCheckBox(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_dis_1.sizePolicy().hasHeightForWidth())
        self.checkBox_dis_1.setSizePolicy(sizePolicy)
        self.checkBox_dis_1.setObjectName("checkBox_dis_1")
        self.gridLayout.addWidget(self.checkBox_dis_1, 0, 0, 1, 1)
        self.checkBox_dis_6 = QtWidgets.QCheckBox(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_dis_6.sizePolicy().hasHeightForWidth())
        self.checkBox_dis_6.setSizePolicy(sizePolicy)
        self.checkBox_dis_6.setObjectName("checkBox_dis_6")
        self.gridLayout.addWidget(self.checkBox_dis_6, 2, 2, 1, 1)
        self.checkBox_dis_3 = QtWidgets.QCheckBox(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_dis_3.sizePolicy().hasHeightForWidth())
        self.checkBox_dis_3.setSizePolicy(sizePolicy)
        self.checkBox_dis_3.setObjectName("checkBox_dis_3")
        self.gridLayout.addWidget(self.checkBox_dis_3, 2, 0, 1, 1)
        self.pushButton_sensors_read = QtWidgets.QPushButton(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sensors_read.sizePolicy().hasHeightForWidth())
        self.pushButton_sensors_read.setSizePolicy(sizePolicy)
        self.pushButton_sensors_read.setObjectName("pushButton_sensors_read")
        self.gridLayout.addWidget(self.pushButton_sensors_read, 3, 0, 1, 1)
        self.pushButton_sensors_write = QtWidgets.QPushButton(sensors_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_sensors_write.sizePolicy().hasHeightForWidth())
        self.pushButton_sensors_write.setSizePolicy(sizePolicy)
        self.pushButton_sensors_write.setObjectName("pushButton_sensors_write")
        self.gridLayout.addWidget(self.pushButton_sensors_write, 3, 2, 1, 1)

        self.retranslateUi(sensors_dialog)
        QtCore.QMetaObject.connectSlotsByName(sensors_dialog)

    def retranslateUi(self, sensors_dialog):
        _translate = QtCore.QCoreApplication.translate
        sensors_dialog.setWindowTitle(_translate("sensors_dialog", "BMS Disable sensors"))
        self.checkBox_dis_4.setText(_translate("sensors_dialog", "TS 1"))
        self.checkBox_dis_2.setText(_translate("sensors_dialog", "Temp 2"))
        self.checkBox_dis_5.setText(_translate("sensors_dialog", "TS 2"))
        self.checkBox_dis_1.setText(_translate("sensors_dialog", "Temp 1"))
        self.checkBox_dis_6.setText(_translate("sensors_dialog", "TS 3"))
        self.checkBox_dis_3.setText(_translate("sensors_dialog", "Temp 3"))
        self.pushButton_sensors_read.setText(_translate("sensors_dialog", "Read"))
        self.pushButton_sensors_write.setText(_translate("sensors_dialog", "Write"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sensors_dialog = QtWidgets.QWidget()
    ui = Ui_sensors_dialog()
    ui.setupUi(sensors_dialog)
    sensors_dialog.show()
    sys.exit(app.exec_())
