# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/update_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fw_update_dialog(object):
    def setupUi(self, fw_update_dialog):
        fw_update_dialog.setObjectName("fw_update_dialog")
        fw_update_dialog.resize(412, 421)
        font = QtGui.QFont()
        font.setPointSize(14)
        fw_update_dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(fw_update_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(fw_update_dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.cb_options = QtWidgets.QCheckBox(fw_update_dialog)
        self.cb_options.setObjectName("cb_options")
        self.gridLayout.addWidget(self.cb_options, 6, 0, 1, 2)
        self.pushButton_updatefw = QtWidgets.QPushButton(fw_update_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_updatefw.sizePolicy().hasHeightForWidth())
        self.pushButton_updatefw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.pushButton_updatefw.setFont(font)
        self.pushButton_updatefw.setObjectName("pushButton_updatefw")
        self.gridLayout.addWidget(self.pushButton_updatefw, 5, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(fw_update_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 10, 0, 1, 2)
        self.lineEdit_fw_version = QtWidgets.QLineEdit(fw_update_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fw_version.sizePolicy().hasHeightForWidth())
        self.lineEdit_fw_version.setSizePolicy(sizePolicy)
        self.lineEdit_fw_version.setObjectName("lineEdit_fw_version")
        self.gridLayout.addWidget(self.lineEdit_fw_version, 2, 1, 1, 1)
        self.input_fwtype = QtWidgets.QLineEdit(fw_update_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_fwtype.sizePolicy().hasHeightForWidth())
        self.input_fwtype.setSizePolicy(sizePolicy)
        self.input_fwtype.setObjectName("input_fwtype")
        self.gridLayout.addWidget(self.input_fwtype, 0, 1, 1, 1)
        self.label_type = QtWidgets.QLabel(fw_update_dialog)
        self.label_type.setObjectName("label_type")
        self.gridLayout.addWidget(self.label_type, 0, 0, 1, 1)
        self.label_info = QtWidgets.QLabel(fw_update_dialog)
        self.label_info.setText("")
        self.label_info.setObjectName("label_info")
        self.gridLayout.addWidget(self.label_info, 7, 0, 1, 2)

        self.retranslateUi(fw_update_dialog)
        QtCore.QMetaObject.connectSlotsByName(fw_update_dialog)

    def retranslateUi(self, fw_update_dialog):
        _translate = QtCore.QCoreApplication.translate
        fw_update_dialog.setWindowTitle(_translate("fw_update_dialog", "BMS Firmware Update"))
        self.label.setText(_translate("fw_update_dialog", "Version"))
        self.cb_options.setText(_translate("fw_update_dialog", "Show options"))
        self.pushButton_updatefw.setText(_translate("fw_update_dialog", "Update"))
        self.input_fwtype.setToolTip(_translate("fw_update_dialog", "<html><head/><body><p>Beyonder: 00</p><p>Äike T: </p><p>customer: 10</p><p>prototype: 1F</p><p>Äike 11: 20</p></body></html>"))
        self.label_type.setText(_translate("fw_update_dialog", "Type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fw_update_dialog = QtWidgets.QWidget()
    ui = Ui_fw_update_dialog()
    ui.setupUi(fw_update_dialog)
    fw_update_dialog.show()
    sys.exit(app.exec_())
